stages:
  - clean
  - build-cml
  - build-nso
  - sync-nso
  - test

image: ghcr.io/model-driven-devops/mdd-container:latestËš

variables:
  ANSIBLE_GATHERING: "smart"
  ANSIBLE_CONFIG: "./ansible.cfg"
  ANSIBLE_ROLES_PATH: "./roles"
  GIT_SUBMODULE_STRATEGY: "recursive"

clean:
  stage: clean
  script:
    - ansible-playbook clean-cml.yml
#  only:
#    changes:
#      - files/arch2.yaml

build-cml:
  stage: build-cml
  script:
    - ansible-playbook build-cml.yml
#  only:
#    changes:
#      - files/arch2.yaml
#
build-nso:
  stage: build-nso
  script:
    - ansible-playbook build-nso.yml
##  only:
##    changes:
##      - files/arch2.yaml
##
sync-nso:
  stage: sync-nso
  script:
    - ansible-playbook sync-nso.yml

test:
  stage: test
  script:
    - ansible-playbook check-network.yml
