- hosts: virl_hosts
  connection: local
  gather_facts: no
  tags:
    - always
  tasks:
    - name: Stop the node
      virl_node:
        host: "{{ virl_host }}"
        user: "{{ virl_username }}"
        password: "{{ virl_password }}"
        name: "{{ inventory_hostname }}"
        lab: "{{ virl_lab }}"
        state: stopped
      tags:
        - stop
        - wipe

    - name: Wipe the node
      virl_node:
        host: "{{ virl_host }}"
        user: "{{ virl_username }}"
        password: "{{ virl_password }}"
        name: "{{ inventory_hostname }}"
        lab: "{{ virl_lab }}"
        state: wiped
      tags:
        - wipe

- hosts: localhost
  connection: local
  gather_facts: no
  tags:
    - always
  tasks:
    - name: Delete the lab
      virl_lab:
        host: "{{ virl_host }}"
        user: "{{ virl_username }}"
        password: "{{ virl_password }}"
        lab: "{{ virl_lab }}"
        state: absent
