- hosts: cml_hosts
  connection: local
  gather_facts: no
  tasks:
    - debug:
        msg: "Node: {{ inventory_hostname }}({{ cml_facts.node_definition }}), State: {{ cml_facts.state }}, Address: {{ hostvars[inventory_hostname]['mgmt_ip'] | default(ansible_host) | ipaddr('address') }}"
    - debug:
        var: virl_facts
      tags:
        - never
        - detail
