- hosts: virl_hosts
  connection: local
  gather_facts: no
  tasks:
    - debug:
        msg: "Node: {{ inventory_hostname }}({{ virl_facts.node_definition }}), State: {{ virl_facts.state }}, Address: {{ hostvars[inventory_hostname]['ansible_host'] | default(ansible_host) }}"
    - debug:
        var: virl_facts
      tags:
        - never
        - detail
