- name: Generate device list
  import_tasks: nso-generateDeviceList.yml
  become: false
  any_errors_fatal: true
  tags:
    - start

- name: Start NSO
  import_tasks: nso-startNSO.yml
  become: false
  any_errors_fatal: true
  tags:
    - start
