---
- name: Process package list
  block:
    - name: Create temporary package holding directory
      tempfile:
        state: directory
        suffix: pkg
      register: tempdir

    - name: Process each package
      include_tasks: nso-installNSOPackage.yml
      loop: "{{ nso_package_list }}"

    - name: Remove temporary package holding directory
      file:
        path: '{{ tempdir.path }}'
        state: absent
  when: nso_package_list is defined